---
system_packages:
  - curl
  - fontconfig
  - fzf
  - git
  - man
  - neovim
  - stow
  - tmux
  - tree
  - unzip
  - wget
  - kubectx

install_terraform_tools: true
terraform_docs_version: "0.19.0"
