---
# zsh_plugins:
#   - { repo: https://github.com/zsh-users/zsh-autosuggestions.git, dest: zsh-autosuggestions }
#   - { repo: https://github.com/zsh-users/zsh-syntax-highlighting.git, dest: zsh-syntax-highlighting }
#   - { repo: https://github.com/zsh-users/zsh-completions.git, dest: zsh-completions }