                                     
---
- name: Automated Linux Setup
  hosts: localhost

  vars_prompt:
    - name: is_wsl
      prompt: "Is this a WSL setup? (yes/no)"
      private: false
      default: "no"

    - name: install_zsh
      prompt: "Do you want to install Zsh? (yes/no)"
      private: false
      default: "no"

  vars_files:
    - group_vars/directories.yml
    - group_vars/packages.yml
    - group_vars/stow.yml
    - group_vars/wsl.yml
    - group_vars/zsh.yml

  roles:
    - ping
    - directories
    - packages
    - role: wsl
      when: is_wsl in ["yes", "y"]
    - stow
    - role: zsh
      when: install_zsh in ["yes", "y"]