---
- name: Install system packages (Debian/RedHat)
  package:
    name: "{{ system_packages }}"
    state: present
  when: ansible_facts['os_family'] in ["Debian", "RedHat"] and system_packages is defined

- name: Include Debian-specific tasks
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install Terraform tools
  include_tasks: terraform.yml
  when: install_terraform_tools