---
- name: Install Zsh
  package:
    name: zsh
    state: present

- name: Clone Zinit
  git:
    repo: https://github.com/zdharma-continuum/zinit.git
    dest: "{{ ansible_env.HOME }}/.local/share/zinit/zinit.git"

- name: Install Starship
  include_tasks: starship.yml

- name: Change default shell to Zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: true