---
- name: Install Zsh
  package:
    name: zsh
    state: present

- name: Ensure ~/.zsh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.zsh"
    state: directory
    mode: 0755

- name: Clone Zsh plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.zsh/{{ item.dest }}"
    depth: 1
  loop: "{{ zsh_plugins }}"
  when: zsh_plugins is defined
  check_mode: no

- name: Download FiraCode Nerd Font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraCode.zip
    dest: /tmp/FiraCode.zip

- name: Extract FiraCode Nerd Font
  unarchive:
    src: /tmp/FiraCode.zip
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    remote_src: yes

- name: Remove temporary files after extraction
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/FiraCode.zip

- name: Refresh font cache
  command:  fc-cache -fv {{ ansible_env.HOME }}/.local/share/fonts

- name: Download and Install Starship
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  args:
    creates: /usr/local/bin/starship

- name: Change default shell to Zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: true