---
- name: Ensure required directories exist
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: 0755
  with_items: "{{ directories_to_create }}"
  when: directories_to_create is defined