---
- name: Ensure required directories exist
  file:
    path: /home/{{ ansible_env.SUDO_USER }}/{{ item }}
    state: directory
    mode: 0755
    owner: "{{ ansible_env.SUDO_USER}}"
    group: "{{ ansible_env.SUDO_USER}}"
  with_items: "{{ directories_to_create }}"
  when: directories_to_create is defined