---
- name: Install Zsh
  package:
    name: zsh
    state: present
  when: install_zsh == "yes"

- name: Change default shell to Zsh
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: "/bin/zsh"
  when: install_zsh == "yes"